### ISSUE TITLE
package dependencies (metric and plot)

### ISSUE THREAD

**Issue by cokelaer** [bioconda/bioconda-paper#9]
@johanneskoester  If you are interested:

- mean number of package dependencies: 3.6
- median number of package dependencies: 2

I can update the Snakefile to produce the histogram of package dependencies

![image](https://user-images.githubusercontent.com/778821/31712315-fa5d73ec-b3fa-11e7-9d35-c47b331f22f2.png)

**Comment by johanneskoester** [comment]
I guess these are first order dependencies?

**Comment by cokelaer** [comment]
Yes indeed

**Comment by johanneskoester** [comment]
Ok, nice! Feel free to provide a pull request. Thank you!
